package com.kaipan.mems.domain;
// Generated 2017-4-27 21:51:34 by Hibernate Tools 4.0.1.Final

/**
 * ExpensemedicalitemId generated by hbm2java
 */
public class ExpensemedicalitemId implements java.io.Serializable {

	private String expenseNum;
	private String medicalNum;

	public ExpensemedicalitemId() {
	}

	public ExpensemedicalitemId(String expenseNum, String medicalNum) {
		this.expenseNum = expenseNum;
		this.medicalNum = medicalNum;
	}

	public String getExpenseNum() {
		return this.expenseNum;
	}

	public void setExpenseNum(String expenseNum) {
		this.expenseNum = expenseNum;
	}

	public String getMedicalNum() {
		return this.medicalNum;
	}

	public void setMedicalNum(String medicalNum) {
		this.medicalNum = medicalNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExpensemedicalitemId))
			return false;
		ExpensemedicalitemId castOther = (ExpensemedicalitemId) other;

		return ((this.getExpenseNum() == castOther.getExpenseNum()) || (this.getExpenseNum() != null
				&& castOther.getExpenseNum() != null && this.getExpenseNum().equals(castOther.getExpenseNum())))
				&& ((this.getMedicalNum() == castOther.getMedicalNum())
						|| (this.getMedicalNum() != null && castOther.getMedicalNum() != null
								&& this.getMedicalNum().equals(castOther.getMedicalNum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getExpenseNum() == null ? 0 : this.getExpenseNum().hashCode());
		result = 37 * result + (getMedicalNum() == null ? 0 : this.getMedicalNum().hashCode());
		return result;
	}

}
