package com.kaipan.mems.domain;
// Generated 2017-4-27 21:51:34 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Expensetype generated by hbm2java
 */
public class Expensetype implements java.io.Serializable {

	private int expenseTyp;
	private int userRoleId;
	private String medicalTyp;
	private int hosptyp;
	private Boolean isRetire;
	private Float thresholdFee;
	private Float expenseProportion;
	private Boolean isDelete;
	private Boolean healthCard;


	public Expensetype() {
	}

	public Expensetype(int expenseTyp, int userRoleId, int hosptyp) {
		this.expenseTyp = expenseTyp;
		this.userRoleId = userRoleId;
		this.hosptyp = hosptyp;
	}

	public Expensetype(int expenseTyp, int userRoleId, String medicalTyp, int hosptyp, Boolean isRetire,
			Float thresholdFee, Float expenseProportion,Boolean isDelete, Boolean healthCard) {
		this.expenseTyp = expenseTyp;
		this.userRoleId = userRoleId;
		this.medicalTyp = medicalTyp;
		this.hosptyp = hosptyp;
		this.isRetire = isRetire;
		this.thresholdFee = thresholdFee;
		this.expenseProportion = expenseProportion;
		this.isDelete=isDelete;
		this.healthCard=healthCard;
//		this.expenses = expenses;
	}

	public int getExpenseTyp() {
		return this.expenseTyp;
	}

	public void setExpenseTyp(int expenseTyp) {
		this.expenseTyp = expenseTyp;
	}

	public int getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(int userRoleId) {
		this.userRoleId = userRoleId;
	}

	public String getMedicalTyp() {
		return this.medicalTyp;
	}

	public void setMedicalTyp(String medicalTyp) {
		this.medicalTyp = medicalTyp;
	}

	public int getHosptyp() {
		return this.hosptyp;
	}

	public void setHosptyp(int hosptyp) {
		this.hosptyp = hosptyp;
	}

	public Boolean getIsRetire() {
		return this.isRetire;
	}

	public void setIsRetire(Boolean isRetire) {
		this.isRetire = isRetire;
	}

	public Float getThresholdFee() {
		return this.thresholdFee;
	}

	public void setThresholdFee(Float thresholdFee) {
		this.thresholdFee = thresholdFee;
	}

	public Float getExpenseProportion() {
		return this.expenseProportion;
	}

	public void setExpenseProportion(Float expenseProportion) {
		this.expenseProportion = expenseProportion;
	}
	
	public Boolean getIsDelete() {
		return isDelete;
	}
	
	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

	public Boolean getHealthCard() {
		return healthCard;
	}
	
	public void setHealthCard(Boolean healthCard) {
		this.healthCard = healthCard;
	}
//	public Set getExpenses() {
//		return this.expenses;
//	}
//
//	public void setExpenses(Set expenses) {
//		this.expenses = expenses;
//	}

}
