package com.kaipan.mems.domain;
// Generated 2017-4-27 21:51:34 by Hibernate Tools 4.0.1.Final

/**
 * ExpensemedicineId generated by hbm2java
 */
public class ExpensemedicineId implements java.io.Serializable {

	private String expenseNum;
	private String medicNum;

	public ExpensemedicineId() {
	}

	public ExpensemedicineId(String expenseNum, String medicNum) {
		this.expenseNum = expenseNum;
		this.medicNum = medicNum;
	}

	public String getExpenseNum() {
		return this.expenseNum;
	}

	public void setExpenseNum(String expenseNum) {
		this.expenseNum = expenseNum;
	}

	public String getMedicNum() {
		return this.medicNum;
	}

	public void setMedicNum(String medicNum) {
		this.medicNum = medicNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExpensemedicineId))
			return false;
		ExpensemedicineId castOther = (ExpensemedicineId) other;

		return ((this.getExpenseNum() == castOther.getExpenseNum()) || (this.getExpenseNum() != null
				&& castOther.getExpenseNum() != null && this.getExpenseNum().equals(castOther.getExpenseNum())))
				&& ((this.getMedicNum() == castOther.getMedicNum()) || (this.getMedicNum() != null
						&& castOther.getMedicNum() != null && this.getMedicNum().equals(castOther.getMedicNum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getExpenseNum() == null ? 0 : this.getExpenseNum().hashCode());
		result = 37 * result + (getMedicNum() == null ? 0 : this.getMedicNum().hashCode());
		return result;
	}

}
