package com.kaipan.mems.domain;
// Generated 2017-4-27 21:51:34 by Hibernate Tools 4.0.1.Final

/**
 * Expensemedicalitem generated by hbm2java
 */
public class Expensemedicalitem implements java.io.Serializable {

	private ExpensemedicalitemId id;
	private Expense expense;
	private Medicalitem medicalitem;
	private String mediaclName;
	private Float medicalUnitPrice;
	private Integer medicalQuantity;
	private Boolean isDelete;

	public Expensemedicalitem() {
	}

	public Expensemedicalitem(ExpensemedicalitemId id, Expense expense, Medicalitem medicalitem) {
		this.id = id;
		this.expense = expense;
		this.medicalitem = medicalitem;
	}

	public Expensemedicalitem(ExpensemedicalitemId id, Expense expense, Medicalitem medicalitem, String mediaclName,
			Float medicalUnitPrice, Integer medicalQuantity, Boolean isDelete) {
		this.id = id;
		this.expense = expense;
		this.medicalitem = medicalitem;
		this.mediaclName = mediaclName;
		this.medicalUnitPrice = medicalUnitPrice;
		this.medicalQuantity = medicalQuantity;
		this.isDelete=isDelete;
	}

	public ExpensemedicalitemId getId() {
		return this.id;
	}

	public void setId(ExpensemedicalitemId id) {
		this.id = id;
	}

	public Expense getExpense() {
		return this.expense;
	}

	public void setExpense(Expense expense) {
		this.expense = expense;
	}

	public Medicalitem getMedicalitem() {
		return this.medicalitem;
	}

	public void setMedicalitem(Medicalitem medicalitem) {
		this.medicalitem = medicalitem;
	}

	public String getMediaclName() {
		return this.mediaclName;
	}

	public void setMediaclName(String mediaclName) {
		this.mediaclName = mediaclName;
	}

	public Float getMedicalUnitPrice() {
		return this.medicalUnitPrice;
	}

	public void setMedicalUnitPrice(Float medicalUnitPrice) {
		this.medicalUnitPrice = medicalUnitPrice;
	}

	public Integer getMedicalQuantity() {
		return this.medicalQuantity;
	}

	public void setMedicalQuantity(Integer medicalQuantity) {
		this.medicalQuantity = medicalQuantity;
	}
	
	public Boolean getIsDelete() {
		return isDelete;
	}
	
	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

}
