package com.kaipan.mems.domain;
// Generated 2017-4-27 21:51:34 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Expense generated by hbm2java
 */
public class Expense implements java.io.Serializable {

	private String expenseNum;
	private Userinfo userinfo;
	private Hospital hospital;
	private Expensetype expensetype;
	private Admininfo admininfo;
	private String userName;
	private String medicalTyp;
	private Float total;
	private Float personsalPay;
	private Float expensePay;
	private Date expenseTime;
	private Integer check;
	private String invoice;
	private Boolean isDelete;
	private Set expensemedicalitems = new HashSet(0);
	private Set expensemedicines = new HashSet(0);

	public Expense() {
	}

	public Expense(String expenseNum, Userinfo userinfo) {
		this.expenseNum = expenseNum;
		this.userinfo = userinfo;
	}

	public Expense(String expenseNum, Userinfo userinfo, Hospital hospital, Expensetype expensetype,
			Admininfo admininfo, String userName, String medicalTyp, Float total, Float personsalPay, Float expensePay,
			Date expenseTime, Integer check, String invoice, Set expensemedicalitems, Set expensemedicines, Boolean isDelete) {
		this.expenseNum = expenseNum;
		this.userinfo = userinfo;
		this.hospital = hospital;
		this.expensetype = expensetype;
		this.admininfo = admininfo;
		this.userName = userName;
		this.medicalTyp = medicalTyp;
		this.total = total;
		this.personsalPay = personsalPay;
		this.expensePay = expensePay;
		this.expenseTime = expenseTime;
		this.check = check;
		this.invoice = invoice;
		this.isDelete=isDelete;
		this.expensemedicalitems = expensemedicalitems;
		this.expensemedicines = expensemedicines;
	}

	public String getExpenseNum() {
		return this.expenseNum;
	}

	public void setExpenseNum(String expenseNum) {
		this.expenseNum = expenseNum;
	}

	public Userinfo getUserinfo() {
		return this.userinfo;
	}

	public void setUserinfo(Userinfo userinfo) {
		this.userinfo = userinfo;
	}

	public Hospital getHospital() {
		return this.hospital;
	}

	public void setHospital(Hospital hospital) {
		this.hospital = hospital;
	}

	public Expensetype getExpensetype() {
		return this.expensetype;
	}

	public void setExpensetype(Expensetype expensetype) {
		this.expensetype = expensetype;
	}

	public Admininfo getAdmininfo() {
		return this.admininfo;
	}

	public void setAdmininfo(Admininfo admininfo) {
		this.admininfo = admininfo;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getMedicalTyp() {
		return this.medicalTyp;
	}

	public void setMedicalTyp(String medicalTyp) {
		this.medicalTyp = medicalTyp;
	}

	public Float getTotal() {
		return this.total;
	}

	public void setTotal(Float total) {
		this.total = total;
	}

	public Float getPersonsalPay() {
		return this.personsalPay;
	}

	public void setPersonsalPay(Float personsalPay) {
		this.personsalPay = personsalPay;
	}

	public Float getExpensePay() {
		return this.expensePay;
	}

	public void setExpensePay(Float expensePay) {
		this.expensePay = expensePay;
	}

	public Date getExpenseTime() {
		return this.expenseTime;
	}

	public void setExpenseTime(Date expenseTime) {
		this.expenseTime = expenseTime;
	}

	public Integer getCheck() {
		return this.check;
	}

	public void setCheck(Integer check) {
		this.check = check;
	}

	public String getInvoice() {
		return this.invoice;
	}

	public void setInvoice(String invoice) {
		this.invoice = invoice;
	}
	
	public Boolean getIsDelete() {
		return isDelete;
	}
	
	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

	public Set getExpensemedicalitems() {
		return this.expensemedicalitems;
	}

	public void setExpensemedicalitems(Set expensemedicalitems) {
		this.expensemedicalitems = expensemedicalitems;
	}

	public Set getExpensemedicines() {
		return this.expensemedicines;
	}

	public void setExpensemedicines(Set expensemedicines) {
		this.expensemedicines = expensemedicines;
	}

}
