package com.kaipan.mems.domain;
// Generated 2017-4-27 21:51:34 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Medicine generated by hbm2java
 */
public class Medicine implements java.io.Serializable {

	private String medicNum;
	private String medicCname;
	private String medicEname;
	private String medicSname;
	private String dosageTyp;
	private String expenseTyp;
	private String medicUnit;
	private Float medicPrice;
	private boolean isExpense;
	private String remark;
	private Boolean isDelete;
//	private Set expensemedicines = new HashSet(0);

	public Medicine() {
	}

	public Medicine(String medicNum, String medicCname, boolean isExpense) {
		this.medicNum = medicNum;
		this.medicCname = medicCname;
		this.isExpense = isExpense;
	}

	public Medicine(String medicNum, String medicCname, String medicEname, String medicSname, String dosageTyp,
			String expenseTyp, String medicUnit, Float medicPrice, boolean isExpense, String remark, Boolean isDelete
			) {
		this.medicNum = medicNum;
		this.medicCname = medicCname;
		this.medicEname = medicEname;
		this.medicSname = medicSname;
		this.dosageTyp = dosageTyp;
		this.expenseTyp = expenseTyp;
		this.medicUnit = medicUnit;
		this.medicPrice = medicPrice;
		this.isExpense = isExpense;
		this.remark = remark;
		this.isDelete=isDelete;
//		this.expensemedicines = expensemedicines;
	}

	public String getMedicNum() {
		return this.medicNum;
	}

	public void setMedicNum(String medicNum) {
		this.medicNum = medicNum;
	}

	public String getMedicCname() {
		return this.medicCname;
	}

	public void setMedicCname(String medicCname) {
		this.medicCname = medicCname;
	}

	public String getMedicEname() {
		return this.medicEname;
	}

	public void setMedicEname(String medicEname) {
		this.medicEname = medicEname;
	}

	public String getMedicSname() {
		return this.medicSname;
	}

	public void setMedicSname(String medicSname) {
		this.medicSname = medicSname;
	}

	public String getDosageTyp() {
		return this.dosageTyp;
	}

	public void setDosageTyp(String dosageTyp) {
		this.dosageTyp = dosageTyp;
	}

	public String getExpenseTyp() {
		return this.expenseTyp;
	}

	public void setExpenseTyp(String expenseTyp) {
		this.expenseTyp = expenseTyp;
	}

	public String getMedicUnit() {
		return this.medicUnit;
	}

	public void setMedicUnit(String medicUnit) {
		this.medicUnit = medicUnit;
	}

	public Float getMedicPrice() {
		return this.medicPrice;
	}

	public void setMedicPrice(Float medicPrice) {
		this.medicPrice = medicPrice;
	}

	public boolean isIsExpense() {
		return this.isExpense;
	}

	public void setIsExpense(boolean isExpense) {
		this.isExpense = isExpense;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	public Boolean getIsDelete() {
		return isDelete;
	}
	
	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

//	public Set getExpensemedicines() {
//		return this.expensemedicines;
//	}
//
//	public void setExpensemedicines(Set expensemedicines) {
//		this.expensemedicines = expensemedicines;
//	}

}
