package com.kaipan.mems.domain;
// Generated 2017-4-27 21:51:34 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Medicalitem generated by hbm2java
 */
public class Medicalitem implements java.io.Serializable {

	private String medicalNum;
	private String medicalName;
	private String expenseTyp;
	private String medicUnit;
	private Float medicalPrice;
	private boolean isExpense;
	private String remark;
	private Boolean isDelete;
	private String imgsrc;
//	private Set expensemedicalitems = new HashSet(0);

	public Medicalitem() {
	}

	public Medicalitem(String medicalNum, String medicalName, boolean isExpense) {
		this.medicalNum = medicalNum;
		this.medicalName = medicalName;
		this.isExpense = isExpense;
	}

	public Medicalitem(String medicalNum, String medicalName, String expenseTyp, String medicUnit, Float medicalPrice,
			boolean isExpense, String remark, Boolean isDelete, String imgsrc) {
		this.medicalNum = medicalNum;
		this.medicalName = medicalName;
		this.expenseTyp = expenseTyp;
		this.medicUnit = medicUnit;
		this.medicalPrice = medicalPrice;
		this.isExpense = isExpense;
		this.remark = remark;
		this.isDelete=isDelete;
		this.imgsrc=imgsrc;
//		this.expensemedicalitems = expensemedicalitems;
	}

	public String getMedicalNum() {
		return this.medicalNum;
	}

	public void setMedicalNum(String medicalNum) {
		this.medicalNum = medicalNum;
	}

	public String getMedicalName() {
		return this.medicalName;
	}

	public void setMedicalName(String medicalName) {
		this.medicalName = medicalName;
	}

	public String getExpenseTyp() {
		return this.expenseTyp;
	}

	public void setExpenseTyp(String expenseTyp) {
		this.expenseTyp = expenseTyp;
	}

	public String getMedicUnit() {
		return this.medicUnit;
	}

	public void setMedicUnit(String medicUnit) {
		this.medicUnit = medicUnit;
	}

	public Float getMedicalPrice() {
		return this.medicalPrice;
	}

	public void setMedicalPrice(Float medicalPrice) {
		this.medicalPrice = medicalPrice;
	}

	public boolean isIsExpense() {
		return this.isExpense;
	}

	public void setIsExpense(boolean isExpense) {
		this.isExpense = isExpense;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	public Boolean getIsDelete() {
		return isDelete;
	}
	
	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}
	
	public String getImgsrc() {
		return imgsrc;
	}
	
	public void setImgsrc(String imgsrc) {
		this.imgsrc = imgsrc;
	}

//	public Set getExpensemedicalitems() {
//		return this.expensemedicalitems;
//	}
//
//	public void setExpensemedicalitems(Set expensemedicalitems) {
//		this.expensemedicalitems = expensemedicalitems;
//	}

}
