package com.kaipan.mems.domain;
// Generated 2017-4-27 21:51:34 by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * Privateletter generated by hbm2java
 */
public class Privateletter implements java.io.Serializable {

	private String pletId;
	private String sender;
	private String receiver;
	private String pletContent;
	private Date pletTime;
	private Boolean pletStatus;
	private Boolean isDelete;

	public Privateletter() {
	}

	public Privateletter(String pletId) {
		this.pletId = pletId;
	}

	public Privateletter(String pletId, String sender, String receiver, String pletContent, Date pletTime,
			Boolean pletStatus, Boolean isDelete) {
		this.pletId = pletId;
		this.sender = sender;
		this.receiver = receiver;
		this.pletContent = pletContent;
		this.pletTime = pletTime;
		this.pletStatus = pletStatus;
		this.isDelete=isDelete;
	}

	public String getPletId() {
		return this.pletId;
	}

	public void setPletId(String pletId) {
		this.pletId = pletId;
	}

	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	public String getReceiver() {
		return this.receiver;
	}

	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}

	public String getPletContent() {
		return this.pletContent;
	}

	public void setPletContent(String pletContent) {
		this.pletContent = pletContent;
	}

	public Date getPletTime() {
		return this.pletTime;
	}

	public void setPletTime(Date pletTime) {
		this.pletTime = pletTime;
	}

	public Boolean getPletStatus() {
		return this.pletStatus;
	}

	public void setPletStatus(Boolean pletStatus) {
		this.pletStatus = pletStatus;
	}
	
	public Boolean getIsDelete() {
		return isDelete;
	}
	
	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

}
